### ISSUE TITLE
我能自己修改、添加模板吗？

### ISSUE THREAD

**Issue by nsxz945** [RalfZhang/File-Template#1]

**Comment by RalfZhang** [comment]
当然可以

**Comment by RalfZhang** [comment]
抱歉，我看错 repo 了……（最近收到另一个项目的 repo 比较多

暂时不支持自己添加模板，如果有需要的语言类型模板，您可以在该 issue 下提出，我会尽快添加
（甚至于您直接提交 pr

**Comment by nsxz945** [comment]
我之前用的是sublime，里面的模板插件sublimeTMPL挺好用的。
我看了下你的代码，好像是根据格式，使用拼接的方式生成模板。
而那个插件里面，每种格式的模板按照一定格式，单独成一个文件，时间戳、作者等信息以变量存在，其他固定的东西就可以直接写着就行了。使用的时候，使用控制台选择对应的模板。这样做的好处就是用户自己编辑、添加模板会很容易，而且同一个格式可以对应多个不同模板。

**Comment by RalfZhang** [comment]
对，我也参考了 sublime 那个，然后我懒得处理文件读取，然后就这样简单粗暴了……
我过段时间有空了补这个坑……
（不过如果你能新开一个 branch 也是极好的……

**Comment by JohnDn** [comment]
希望作者把react-native的模板也添加一下😆

**Comment by RalfZhang** [comment]
@JohnDn 关于这个模板有没有什么建议，或者你提供一份我直接改改就加上去

**Comment by RalfZhang** [comment]
@nsxz945 已更新为模板文件读取模式，个人可以修改模板内容
