### ISSUE TITLE
运行命令报错

### ISSUE THREAD

**Issue by Cheng007** [RalfZhang/File-Template#2]
环境：
win7，vsc1.18.0

执行过程：
1、Ctrl + Shift + P
2、输入tmpl: create template并回车

报如下错误：
Running the contributed command:'extension.tmpl' failed.

**Comment by RalfZhang** [comment]
对什么类型/后缀名的文件进行这样的操作的？

**Comment by Cheng007** [comment]
操作失误，在没有打开文件的情况下运行了命令

**Comment by RalfZhang** [comment]
I updated error info just now.
