### ISSUE TITLE
怎么设置自己的变量？

### ISSUE THREAD

**Issue by MaiXiaochai** [RalfZhang/File-Template#4]
# @Date    : ${date}
# @Author  : ${1:Your Name} (${2:you@example.org})
# @Link    : ${3:link}
# @Version : ${4:1.0.0}
像这些变量的含义都是什么？${date}我知道，变量的语法是什么？怎么添加自己的变量？

**Comment by RalfZhang** [comment]
Edit template in https://github.com/RalfZhang/File-Template#more
